CREATE TABLE fin_statement (
    id                        CHAR(36) NOT NULL,
    ticker_symbol             VARCHAR(10) NOT NULL COMMENT '証券コード',
    stock_brand_id            CHAR(36) NULL COMMENT '銘柄ID',
    disclosed_date            DATE NOT NULL COMMENT '開示日',
    fiscal_year_end           DATE NULL COMMENT '当期末日',
    type_of_document          VARCHAR(64) NULL COMMENT '開示書類種別',
    type_of_current_period    VARCHAR(10) NULL COMMENT '当会計期間の種類',
    net_sales                 DECIMAL(20,2) NULL COMMENT '売上高',
    operating_profit          DECIMAL(20,2) NULL COMMENT '営業利益',
    ordinary_profit           DECIMAL(20,2) NULL COMMENT '経常利益',
    profit                    DECIMAL(20,2) NULL COMMENT '当期純利益',
    earnings_per_share        DECIMAL(20,4) NULL COMMENT 'EPS',
    book_value_per_share      DECIMAL(20,4) NULL COMMENT 'BPS',
    forecast_net_sales        DECIMAL(20,2) NULL COMMENT '通期予想売上高',
    forecast_operating_profit DECIMAL(20,2) NULL COMMENT '通期予想営業利益',
    forecast_profit           DECIMAL(20,2) NULL COMMENT '通期予想純利益',
    forecast_eps              DECIMAL(20,4) NULL COMMENT '通期予想EPS',
    created_at                DATETIME NOT NULL,
    updated_at                DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_statement (ticker_symbol, disclosed_date, type_of_document),
    INDEX idx_statement_symbol (ticker_symbol)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
