-- daily_stock_pick 引け後スクリーニングで選定した「翌営業日の買い候補」。
-- 後日の答え合わせ結果（1/3/5営業日後リターン・勝敗）を同じ行に UPDATE で書き戻す。
CREATE TABLE IF NOT EXISTS `stock_price_repository`.`daily_stock_pick` (
  `pick_date` DATE NOT NULL COMMENT '選定基準日（この日の引け値でスクリーニング。翌営業日の寄り〜引けで買う想定）',
  `stock_brand_id` CHAR(36) NOT NULL COMMENT 'stock_brand.id',
  `ticker_symbol` VARCHAR(10) NOT NULL COMMENT '銘柄コード',
  `pick_rank` INT UNSIGNED NOT NULL COMMENT 'スコア降順の順位 1..N（rank は MySQL8 予約語のため pick_rank）',
  `score` DECIMAL(5, 2) NOT NULL COMMENT '複合スコア 0.00-100.00',
  `score_version` VARCHAR(16) NOT NULL COMMENT 'スコア定義バージョン。重み変更時にインクリメントし過去分と混ぜて集計しない',
  `signal_count` TINYINT UNSIGNED NOT NULL COMMENT '最新営業日に点灯した基本4戦略の数 1-4',
  `strategies` VARCHAR(255) NOT NULL COMMENT '点灯戦略キーのカンマ区切り 例: macd_bullish,ma_cross',
  `sector_33_code_name` VARCHAR(64) NULL COMMENT '33業種名。セクター分散上限の効き具合を後から検証するため保存',
  `base_close_price` DECIMAL(10, 4) NOT NULL COMMENT 'pick_date の終値（Slack表示・目視確認用のスナップショット）',
  `base_adj_close_price` DECIMAL(10, 4) NOT NULL COMMENT 'pick_date の調整後終値。答え合わせリターンの基準価格 P0',
  `avg_trading_value` DECIMAL(24, 4) NOT NULL COMMENT '直近20営業日平均売買代金 volume*close',
  `volume_ratio` DECIMAL(10, 4) NOT NULL COMMENT '当日出来高 / 直近20営業日平均出来高',
  `adx` DECIMAL(8, 4) NOT NULL COMMENT 'ADX(14)',
  `plus_di` DECIMAL(8, 4) NOT NULL COMMENT '+DI(14)',
  `minus_di` DECIMAL(8, 4) NOT NULL COMMENT '-DI(14)',
  `atr_ratio` DECIMAL(10, 6) NOT NULL COMMENT 'ATR(14) / 終値',
  `rsi` DECIMAL(8, 4) NOT NULL COMMENT 'RSI(14)',
  `return_1d` DECIMAL(12, 6) NULL COMMENT '1営業日後リターン（base_adj_close_price 基準）。未到来は NULL',
  `return_3d` DECIMAL(12, 6) NULL COMMENT '3営業日後リターン。未到来は NULL',
  `return_5d` DECIMAL(12, 6) NULL COMMENT '5営業日後リターン。未到来は NULL',
  `outcome` VARCHAR(16) NULL COMMENT '勝敗判定: win/lose/draw/void。return_5d 基準',
  `evaluated_at` DATETIME NULL COMMENT '答え合わせ確定日時。NULL の行だけが答え合わせバッチの対象',
  `notified_at` DATETIME NULL COMMENT 'Slack 通知日時。NULL なら未通知＝次回バッチで再通知する',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created_at',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated_at',
  PRIMARY KEY (`pick_date`, `stock_brand_id`),
  UNIQUE KEY `uk_daily_stock_pick_date_rank` (`pick_date`, `pick_rank`),
  KEY `idx_daily_stock_pick_evaluated_at` (`evaluated_at`, `pick_date`),
  KEY `idx_daily_stock_pick_stock_brand_id` (`stock_brand_id`),
  FOREIGN KEY (`stock_brand_id`) REFERENCES stock_brand (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
